# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f8a1cd1984ee6dc33b0979c3fd1576222164606cd9f0beedc5be4a27bf046be5c9fd680ebadc13cf757a98d75f4cb27eba2c71464735f1a79c57b8a5d28c75e

test:
  secret_key_base: f7d72e19dd44f2e156b38fb3810e9ac93f954327b069edaf68e74bd14fee94e7ad982c9736d4697e4dbdb8d317687832d9db38b2c402a12e90d63c6f44166828

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
